version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - my_custom_network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my_custom_network

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/chat-app
    networks:
      - my_custom_network

volumes:
  redis-data:
  mongo-data:

networks:
  my_custom_network:
    driver: bridge
